ExamenDDI_Sergio/ExamenDDI_Ale/Models/Carro.cs
Pou porpper

ExamenDDI_Sergio/ExamenDDI_Ale/Models/ErrorViewModel.cs
namespace ExamenDDI_Sergio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamenDDI_Sergio/ExamenDDI_Ale/Controllers/HomeController.cs
using ExamenDDI_Sergio.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ExamenDDI_Sergio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamenDDI_Sergio/ExamenDDI_Ale/Controllers/MovieCallController.cs
using ExamenDDI_Ale.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ExamenDDI_Ale.Controllers
{
    public class MovieCallController : Controller
    {
        private readonly TMDbService _tmdbService;

        public MovieCallController(TMDbService tmdbService)
        {
            _tmdbService = tmdbService;
        }

        public async Task<IActionResult> NowPlaying()
        {
            var movies = await _tmdbService.GetNowPlayingMoviesAsync();
            return View(movies);
        }
    }
}

/* 
APB Ardillas por doquier

ven mas cerca y mirarme bailar
Main in the mirror
*/

ExamenDDI_Sergio/ExamenDDI_Ale/Controllers/NewController.cs
Esto es una prueba y se borrara.

ExamenDDI_Sergio/ExamenDDI_Ale/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamenDDI_Sergio/ExamenDDI_Ale/Views/MovieCall/NowPlaying.cshtml
@model List<ExamenDDI_Ale.Service.Movie>

<h1>Lista de Peliculas</h1>

<div class="row row-cols-1 row-cols-md-3 g-4">
@foreach (var movie in Model)
{
    <div class="col">
        <div class="card  h-100">
        <div class="card-header">
            <h2>@movie.Title</h2>
        </div>
        <div class="card-body">
                <img src="https://image.tmdb.org/t/p/w500/@movie.Poster_Path" alt="Poster of @movie.Title" height="250" width="150" />
        </div>
        <div class="card-footer">
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">
                Detalles
            </button>
        </div>
    </div>
    </div>

    <!-- The Modal -->
    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Detalles</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <p>@movie.Overview</p>
                </div>
            </div>
        </div>
    </div>
}
</div>

ExamenDDI_Sergio/ExamenDDI_Ale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamenDDI_Ale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExamenDDI_Sergio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamenDDI_Ale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NowPlaying" asp-controller="MovieCall" asp-action="NowPlaying">Api</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExamenDDI_Sergio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>